services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - ./dummy_data/data:/docker-entrypoint-initdb.d/data:ro
      - ./sql/init_dummy.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  db2:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: admin2
      POSTGRES_DB: test2
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
